### ISSUE TITLE
[Feature Request] SSR没有Protocol Param

### ISSUE THREAD

**Issue by lslzl3000** [ShadowsocksR-Live/iShadowsocksR#10]
终于编译成功，但是发现并没有提供SSR Protocol Param的设置
原版之前的shadowsocks-libev库确实比较老，不支持各种参数和加密方式
但是这个版本所有库都是最新的了，是可以支持Protocol Param的，不知大神有没有兴趣加上？

**Comment by ssrlive** [comment]
指望你提pr了。

**Comment by aishuidedabai** [comment]
直接加啊，这个特么的不复杂，最复杂的部分，还没弄明白libev的代码顺序

**Comment by ssrlive** [comment]
这么烂的 libev 代码不值得再碰。

**Comment by 598059069** [comment]
很容易加啊 我已经加好了 不过我不知道怎么更新上去

**Comment by 598059069** [comment]
这个SSR底层支持全局代理不  你们知道不？ 要怎么配置？

**Comment by azhm** [comment]
@598059069 老哥提交上来呀

**Comment by aishuidedabai** [comment]
acl

**Comment by azhm** [comment]
支持全局呀  app首页不就有个全局开关么

**Comment by ssrlive** [comment]
@598059069 你提交 PR 吧.

**Comment by Creolophus** [comment]
我也改了，需要的话我可以提pr

**Comment by ssrlive** [comment]
提吧.

**Comment by aishuidedabai** [comment]
谁能给个v2的集成教程

ssrlive <notifications@github.com>于2019年10月9日 周三20:20写道：

**Comment by VesenGu** [comment]
按教程合下来添加了Protocol Param参数在dug模式下可以正常使用，但是在release下同样的ssr配置回出现链接秒断的情况，请问大佬怎么解决呀？

**Comment by ssrlive** [comment]
https://github.com/ShadowsocksR-Live/iShadowsocksR/issues/30#issuecomment-536197706

**Comment by VesenGu** [comment]
可以了，十分感谢

**Comment by ssrlive** [comment]
@VesenGu 彻底在我视野里消失吧。不想再见到你。
