### ISSUE TITLE
对比小火箭，好像少了添加socks5的功能，我可以直接在你的源代码上加入吗？

### ISSUE THREAD

**Issue by zhiYong964941772** [ShadowsocksR-Live/iShadowsocksR#100]
![IMG_8330](https://github.com/user-attachments/assets/c3f425e4-6a6a-4dfe-95c7-aab4c0577b0d)

**Comment by ssrlive** [comment]
那你試着提交一個 PR 吧。

**Comment by ssrlive** [comment]
那你試着提交一個 PR 吧。其實我不知道有什麼實際用途。因爲 GFW 會光速封殺 位於 外網 的 SOcks5 服務端，只要你膽敢直連。

**Comment by zhiYong964941772** [comment]
可以给我提供一些思路嘛，我看到好多库都用不了，一开始我甚至接入了HevSocks5Tunnel,但并没什么效果，数据转发不到Socks5服务器。

**Comment by ssrlive** [comment]
由於 本項目已經集成 了 badvpn-tun2socks 組件，也就是說，從 Tun 出來的數據已經轉換成 socks5 協議的數據了， 這時候直接告訴 tun2socks 組件目標 服務器和端口 就可以正常工作了。

**Comment by zhiYong964941772** [comment]
好的，我深入研究一下，有问题再请教大佬您
