### ISSUE TITLE
iShadowsocksR支持全局代理不？？要如何才能支持？

### ISSUE THREAD

**Issue by 598059069** [ShadowsocksR-Live/iShadowsocksR#13]
我已经运行成功了，看了底层的代码逻辑，发现有一个默认配置TCP_ONLY， 以为把它改成UDP_ONLY就能实现全局代理了，结果发现不行。

**Comment by ssrlive** [comment]
TCP_ONLY 已经被抛弃. 也就是说, 必须代理 TCP 流量. 而不能只代理 UDP 流量.

**Comment by ssrlive** [comment]
貌似目前只支持全局代理. 不分兲朝美国. 一概走代理.

**Comment by FatChou** [comment]
@ssrlive 支持UDP转发吗？
