### ISSUE TITLE
运行./build-libssl.sh这步没成功

### ISSUE THREAD

**Issue by uhavemysword** [ShadowsocksR-Live/iShadowsocksR#16]
openssl git:(bc0adc8) ./build-libssl.sh

Build options
  OpenSSL version: 1.0.2l
  Architectures: x86_64 i386 arm64 armv7s armv7 tv_x86_64 tv_arm64
  iOS SDK: 11.4
  tvOS SDK: 11.4
  Number of make threads: 8
  Build location: /Users/David/Desktop/FQ/iShadowsocksR/Library/openssl

Using openssl-1.0.2l.tar.gz
Building openssl-1.0.2l for iPhoneSimulator 11.4 x86_64...
  Logfile: /Users/David/Desktop/FQ/iShadowsocksR/Library/openssl/bin/iPhoneSimulator11.4-x86_64.sdk/build-openssl-1.0.2l.log
  Configure...
  Patching Makefile...
  Make (using 8 thread(s))...
Problem during make - Please check /Users/David/Desktop/FQ/iShadowsocksR/Library/openssl/bin/iPhoneSimulator11.4-x86_64.sdk/build-openssl-1.0.2l.log

log的结果

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive member: ../../libcrypto.a(ec_key.o) size too large (archive member extends past the end of the file)
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar: internal ranlib command failed
make[2]: *** [lib] Error 1
make[1]: *** [subdirs] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [build_crypto] Error 1

**Comment by ssrlive** [comment]
"size too large" ---- 硬盘空间耗尽.

**Comment by uhavemysword** [comment]
> "size too large" ---- 硬盘空间耗尽.

不是硬盘空间的问题......我的硬盘够的

**Comment by weqeo** [comment]
> > "size too large" ---- 硬盘空间耗尽.
> 
> 不是硬盘空间的问题......我的硬盘够的

我也碰到同样的问题了，请问你解决了吗？

**Comment by ssrlive** [comment]
我没有遇到过
