### ISSUE TITLE
UDP超时处理错误

### ISSUE THREAD

**Issue by aishuidedabai** [ShadowsocksR-Live/iShadowsocksR#18]
建议这样写
 [self.udpSocket sendData:outData toHost:destHost port:ntohs(udphdr->dest) withTimeout:-1 tag:0];//443

**Comment by XuCe** [comment]
是的 这样写 我发现udp 正常了

**Comment by XuCe** [comment]
@aishuidedabai  是的 这样写 我发现udp 正常了
