### ISSUE TITLE
在有些情况下libsodium会崩溃

### ISSUE THREAD

**Issue by TheWanderingCoel** [ShadowsocksR-Live/iShadowsocksR#19]
大佬你好,我发现我的在使用需要libsodium加密的时候会崩溃,消息是sodium_set_misuse_handler.
![WX20190522-072210](https://user-images.githubusercontent.com/39617891/58136895-684c9780-7c62-11e9-8b7d-a43cf2308ea9.png)

**Comment by ssrlive** [comment]
你的 配置 去掉 敏感信息 发出来一下。

**Comment by TheWanderingCoel** [comment]
Ip:xxxx
Port:80
Password:xxxxxxxxx
Method:chacha20-ietf
Protocol:auth_aes_128_md5
protocol_param:1:xxxxxx
Ofbs:http_simple
Obfs_param:189.cn

**Comment by TheWanderingCoel** [comment]
只要选择libsodium的算法:chacha20,chacha20-ietf就会崩溃。不是就没有任何问题

**Comment by ssrlive** [comment]
好的。
目前在做 overtls 分支，直接走 https 协议，届时所有加密、协议、混淆 都显多余。

**Comment by TheWanderingCoel** [comment]
已解决,Xcode release的代码优化设置问题。谢谢大佬回复

**Comment by ssrlive** [comment]
代码优化设置有何要注意的细节？最好提交pr

**Comment by TheWanderingCoel** [comment]
设置成弄而不是fastest,不然libsodium直接崩了

**Comment by TheWanderingCoel** [comment]
OPTIMIZATION_LEVEL 设置DEBUG和RELEASE都是None

**Comment by lvpeng0412** [comment]
修改了后release还是闪退，而且还定位不到闪退的位置 @TheWanderingCoel

**Comment by ssrlive** [comment]
https://github.com/ShadowsocksR-Live/iShadowsocksR/issues/30

**Comment by lvpeng0412** [comment]
@ssrlive 感谢，闪退问题解决了
