### ISSUE TITLE
老铁，开启vpn却无法联网

### ISSUE THREAD

**Issue by saminlu** [ShadowsocksR-Live/iShadowsocksR#2]
老铁，首先感谢你能提供个能成功开启vpn的版本，我这个ssr服务器账号在mac在用的，添加到potatso后，在开启vpn却无法联网，这是怎么处理好呢？

**Comment by saminlu** [comment]
并且开启后会断了我的Wi-Fi

**Comment by ssrlive** [comment]
電郵發送你的配置給我看看?

**Comment by TheWanderingCoel** [comment]
大佬,我这边也是同样无法联网诶。直接访问Ip是可以的,打开谷歌显示ERR_FAILED

**Comment by TheWanderingCoel** [comment]
日志有什么Crunch:Connection failure:www.google.com:443

**Comment by fangshufeng** [comment]
我也是这个问题呢，和[这个](https://github.com/haxpor/Potatso/issues/29)是一样，我的GroupID是一样的
