### ISSUE TITLE
Telegram无法被代理(疑似tun2socks问题)

### ISSUE THREAD

**Issue by TheWanderingCoel** [ShadowsocksR-Live/iShadowsocksR#20]
大佬好,不好意思又打扰了。之前看到大佬您说2018年tg更新过代码就用不了了,我试了下APP Store随机的一个V。P。N,别家的ssr软件(小火箭)都可以正常连接(不用设置代理)。所以很好奇是不是tun2socks的问题。
![img_0726](https://user-images.githubusercontent.com/39617891/58175369-91a50c00-7cd2-11e9-9f42-82741f9a9514.png)

**Comment by ssrlive** [comment]
这个代码库是基于 土豆丝 的，你下载一个 土豆丝 测试版 试试？ 如果 土豆丝 也代理不了 tg 那么，这整个 实现就是有问题的。
但去年某个时间之前的 代码是可以代理 tg 的，当时试过。

**Comment by TheWanderingCoel** [comment]
Potatso Lite 测试版正常
Shadowrocket 正常
Potatso 2 正常

**Comment by ssrlive** [comment]
有个临时解决方案，将 软件内核的 s5 服务器监听端口告诉用户，让用户自行设置 tg 的 s5 代理。

**Comment by TheWanderingCoel** [comment]
嗯,但是有些走TCP的软件不能设置代理就很头疼,希望大佬能解决这个问题吧。“默认走代理”貌似逻辑有问题

**Comment by TheWanderingCoel** [comment]
大概发现问题了,如下:SS代理TGSSR就不代理。可能是Manager.swift有点问题

**Comment by TheWanderingCoel** [comment]
case .Shadowsocks下面加入:
```Swift
// 修复SSR不能使用Telegram
            case .ShadowsocksR:
                let uriString = "socks5://127.0.0.1:${ssport}"
                let uri = XMLElement.element(withName: "uri", children: nil, attributes: [XMLNode.attribute(withName: "value", stringValue: uriString) as! DDXMLNode]) as! XMLElement
                chain.addChild(uri)
                let authscheme = XMLElement.element(withName: "authscheme", children: nil, attributes: [XMLNode.attribute(withName: "value", stringValue: "anonymous") as! DDXMLNode]) as! XMLElement
                chain.addChild(authscheme)
```
搞定,谢谢大佬回复

**Comment by ssrlive** [comment]
谢谢修复。晚些时候合并。

**Comment by ssrlive** [comment]
@TheWanderingCoel  希望你花点时间测试一下 WhatsApp 和 line 我没有试过。

**Comment by TheWanderingCoel** [comment]
好的,有空测试下

**Comment by TheWanderingCoel** [comment]
经测试都可以正常使用

**Comment by ssrlive** [comment]
好的感谢

**Comment by ssrlive** [comment]
请问你有 linuv websocket nginx 开发使用背景吗？ 目前 ssr-n 的 tls 分支卡在了数据接收不完整上，几天没有进展。

**Comment by TheWanderingCoel** [comment]
很抱歉我估计帮不上什么忙。我只使用过nginx。最近有个项目叫trojan，就是overtls。或许对你有些帮助

**Comment by ssrlive** [comment]
正在研究这个项目。一坨一坨的boost狗屎看得人烦恶欲呕。

**Comment by TheWanderingCoel** [comment]
大佬，我又开了一个issue，有一些发现的问题，希望能解决一下，谢谢。
