### ISSUE TITLE
 'Attribute' is not a member type of 'NSLayoutConstraint'

### ISSUE THREAD

**Issue by wf2000cn** [ShadowsocksR-Live/iShadowsocksR#21]
<img width="1897" alt="image" src="https://user-images.githubusercontent.com/7960748/58384157-2e3c1680-8011-11e9-98e3-6c4127bae37d.png">

**Comment by ssrlive** [comment]
我的 IDE 是 Xcode 10.1 ， 没有报错， 不知 你的版本是啥。

**Comment by wf2000cn** [comment]
首先感谢老兄努力付出！赞👍！我看你推荐的xcode9.2我就去下载了9.2.然后按照你写的流程一步步把submodule，pod都装了，到openssl的时候没有过去（我看你有回复别人硬盘空间不够，我这边硬盘空间是够的）。不过我想先编译下看还有什么错先解决了。然后一次解决了signing问题，pkcs7.h找不到问题， Library not found for -lcrypto问题，然后到这过不去了。

**Comment by ssrlive** [comment]
改完了。
