### ISSUE TITLE
编译成功并上传到了 App Store，然后使用 TestFlight 安装测试，但始终无法连接上代理服务。

### ISSUE THREAD

**Issue by jaggerwang** [ShadowsocksR-Live/iShadowsocksR#22]
查看日志一直提示“start proxy: shadowsocks error: timeout”。代理服务器没问题，自己搭建的和第三方的都试过，这些代理服务在 macOS 上都是可以连接的。

![IMG_4872](https://user-images.githubusercontent.com/1255011/58558601-d50ff500-8253-11e9-9a71-5547cb144811.png)

**Comment by ssrlive** [comment]
我也不确定是为什么。
但肯定的是：
不能使用 release 编译；
不能在上传过程中中断，断点续传也不行；
依据项目许可证，不准公开发布。

**Comment by jaggerwang** [comment]
没打算公开发布，就自个儿用。找到原因了，从 TestFlight 安装后没有提示授权网络访问。通过 XCode 调试运行有提示授权，然后再重新从 TestFlight 安装就可用了。感谢！
