### ISSUE TITLE
openssl cannot compile using Mojave 10.14.3

### ISSUE THREAD

**Issue by zonzi** [ShadowsocksR-Live/iShadowsocksR#24]
after checks, this issue seems related to specific MacOs Mojave 10.14.3 version.
Tried to the solution to reinstall the headers on stackoverflow and it doesn't work in my case.
Just leave a trace in case someone knows how to fix.

[Can't compile C program on a Mac after upgrade to Mojave](https://stackoverflow.com/questions/52509602/cant-compile-c-program-on-a-mac-after-upgrade-to-mojave) 

120:6211: fatal error: :fatal error11fatal error: : 'stdlib.h' file not found#include <stdio.h>
'stdlib.h' file not found

**Comment by ssrlive** [comment]
maybe [this](https://github.com/x2on/OpenSSL-for-iPhone/issues/172) is a solution.

**Comment by zonzi** [comment]
thank you, I'll have a look..

**Comment by zonzi** [comment]
I tried to upgrade the mac os to macos 10.14.5 and I have also tried to compile the code below
`#include <stdio.h>
int main() {
  puts("Hi");
  return 0;
}`
into test.c
`$ gcc -o test test.c`
works and by executing  the code seems ok...
`$ ./test
Hi`
....
don't know why the openssl cannot found the header file...
I have also tried to change the compile flags in openssl build script, but the error remains the same...

**Comment by ssrlive** [comment]
@zonzi 下面这个脚本希望你能测试一下. 如果没问题, 我把 它 合并过来.
https://github.com/eyvallah/openssl-apple

**Comment by zonzi** [comment]
hi ssrlive, I have tried those scripts and they don't work.
I had the same message as this one and it seems not resolved yet.
https://github.com/avast/retdec/issues/439
