### ISSUE TITLE
有几个奇怪的bug想提问下

### ISSUE THREAD

**Issue by TheWanderingCoel** [ShadowsocksR-Live/iShadowsocksR#25]
都是有关ssr-native这个后端的。
第一个就是测速会有瓶颈30Mbps左右,别家软件能跑满(开代理的情况)
第二就是speedtest上传测速的时候,上传到一般显示测速错误。可能跟之前有人说明的ins和youtube上传也相关。
第三个就是直连的时候也是跑不满宽带,200Mbps只能跑到100Mbps,别家没有问题。
希望大佬能解决下,谢谢

**Comment by ssrlive** [comment]
好的. 这只能等当前重要工作完毕以后才能着手了.

**Comment by ssrlive** [comment]
你再测试一下上传. 估计目前问题已经解决了.
