### ISSUE TITLE
运行./build-libssl.sh 这步报错了

### ISSUE THREAD

**Issue by weqeo** [ShadowsocksR-Live/iShadowsocksR#26]
打印日志如下：
> /Applications/Xcode.app/Contents/Developer/usr/bin/gcc -arch x86_64 -I.. -I../.. -I../modes -I../asn1 -I../evp -I../../include  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.1.sdk  -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -fembed-bitcode -miphoneos-version-min=7.0 -arch x86_64 -O3 -DL_ENDIAN -Wall   -c -o obj_err.o obj_err.c
/Applications/Xcode.app/Contents/Developer/usr/bin/gcc -arch x86_64 -I.. -I../.. -I../modes -I../asn1 -I../evp -I../../include  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.1.sdk  -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -fembed-bitcode -miphoneos-version-min=7.0 -arch x86_64 -O3 -DL_ENDIAN -Wall   -c -o obj_xref.o obj_xref.c
ar  r ../../libcrypto.a o_names.o obj_dat.o obj_lib.o obj_err.o obj_xref.o
ar: ar: creating archive ../libcrypto.a
../../libcrypto.a: Inappropriate file type or format
make[2]: *** [lib] Error 1
make[1]: *** [subdirs] Error 1
make[1]: *** Waiting for unfinished jobs....
test -z "" || ar  r ../libcrypto.a fipscanister.o
/usr/bin/ranlib ../libcrypto.a || echo Never mind.
make: *** [build_crypto] Error 1

**Comment by ssrlive** [comment]
请到 这里提 issue . 两年没维护了. 也不知道管用不. https://github.com/x2on/OpenSSL-for-iPhone/issues

**Comment by weqeo** [comment]
> 请到 这里提 issue . 两年没维护了. 也不知道管用不. https://github.com/x2on/OpenSSL-for-iPhone/issues

好的，谢谢～

**Comment by ssrlive** [comment]
如果你改好了, 可以直接向 我提 PR. 这是我维护的fork.
https://github.com/ShadowsocksR-Live/OpenSSL-for-iPhone/pulls

**Comment by weqeo** [comment]
> 如果你改好了, 可以直接向 我提 PR. 这是我维护的fork.
> https://github.com/ShadowsocksR-Live/OpenSSL-for-iPhone/pulls

好的～

**Comment by weqeo** [comment]
绕了一大圈，原来还是版本太低的问题，编译openSSL的时候执行`./build-libssl.sh --version=1.1.0f`就可以了，而不是执行`./build-libssl.sh`，如果执行`./build-libssl.sh`，默认会安装的openSSL版本是**1.0.2l**，这个版本在iOS11以上好像都是不支持的

**Comment by ssrlive** [comment]
好的. 我修改 安装说明.
