### ISSUE TITLE
Utils/Receipt.m 编译到最后报错

### ISSUE THREAD

**Issue by lokisama** [ShadowsocksR-Live/iShadowsocksR#28]
Utils/Receipt.m 编译到最后报错。
Mac 10.14.5 (18F132)
Xcode Version 10.1 (10B61)
pod 1.7.3
执行过libssl.sh了，全盘改过id了。最后编译报这个，不太会，感谢大佬指点问题在哪

Implicit declaration of function 'OpenSSL_add_all_digests'
Implicit declaration of function 'EVP_cleanup'

./build-libssl.sh --version=1.1.0f

Build options
  OpenSSL version: 1.1.0f
  Targets: ios-sim-cross-x86_64 ios-sim-cross-i386 ios64-cross-arm64 ios-cross-armv7s ios-cross-armv7 tvos-sim-cross-x86_64 tvos64-cross-arm64
  iOS SDK: 12.1
  tvOS SDK: 12.1
  Number of make threads: 8
  Configure options:  no-deprecated
  Build location: /Users/maji/Documents/git/iShadowsocksR/Library/openssl

Downloading openssl-1.1.0f.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5154k  100 5154k    0     0   571k      0  0:00:09  0:00:09 --:--:--  798k
Building openssl-1.1.0f for iPhoneSimulator 12.1 x86_64...
  Logfile: /Users/maji/Documents/git/iShadowsocksR/Library/openssl/bin/iPhoneSimulator12.1-x86_64.sdk/build-openssl-1.1.0f.log
  Configure...
  Make (using 8 thread(s))...
Building openssl-1.1.0f for iPhoneSimulator 12.1 i386...
  Logfile: /Users/maji/Documents/git/iShadowsocksR/Library/openssl/bin/iPhoneSimulator12.1-i386.sdk/build-openssl-1.1.0f.log
  Configure...
  Make (using 8 thread(s))...
Building openssl-1.1.0f for iPhoneOS 12.1 arm64...
  Logfile: /Users/maji/Documents/git/iShadowsocksR/Library/openssl/bin/iPhoneOS12.1-arm64.sdk/build-openssl-1.1.0f.log
  Configure...
  Make (using 8 thread(s))...
Building openssl-1.1.0f for iPhoneOS 12.1 armv7s...
  Logfile: /Users/maji/Documents/git/iShadowsocksR/Library/openssl/bin/iPhoneOS12.1-armv7s.sdk/build-openssl-1.1.0f.log
  Configure...
  Make (using 8 thread(s))...
Building openssl-1.1.0f for iPhoneOS 12.1 armv7...
  Logfile: /Users/maji/Documents/git/iShadowsocksR/Library/openssl/bin/iPhoneOS12.1-armv7.sdk/build-openssl-1.1.0f.log
  Configure...
  Make (using 8 thread(s))...
Building openssl-1.1.0f for AppleTVSimulator 12.1 x86_64...
  Logfile: /Users/maji/Documents/git/iShadowsocksR/Library/openssl/bin/AppleTVSimulator12.1-x86_64.sdk/build-openssl-1.1.0f.log
  Configure...
  Make (using 8 thread(s))...
Building openssl-1.1.0f for AppleTVOS 12.1 arm64...
  Logfile: /Users/maji/Documents/git/iShadowsocksR/Library/openssl/bin/AppleTVOS12.1-arm64.sdk/build-openssl-1.1.0f.log
  Configure...
  Make (using 8 thread(s))...
Build library for iOS...
Build library for tvOS...

**Comment by shaoshi-kin** [comment]
./build-libssl.sh, 不要后面的版本，我去掉后可以了

**Comment by shaoshi-kin** [comment]
./build-libssl.sh
