### ISSUE TITLE
打包后代理失败

### ISSUE THREAD

**Issue by XuCe** [ShadowsocksR-Live/iShadowsocksR#30]
我真机调试 加密方式选chacha20 协议选auth_aes128_md5 混淆选tls1.2_ticket_auth 能正常打开外网。打包发布之后 这配置 网页打开 报错。但是我把配置改成 rc4-md5 origin plain 能正常访问。什么原因 求助！！！

**Comment by ssrlive** [comment]
改成这一行再试试。
https://github.com/ShadowsocksR-Live/shadowsocksr-native/blob/master/src/encrypt.c#L1184

**Comment by XuCe** [comment]
nice 可以了。

**Comment by rongshuizhou** [comment]
请问你们是怎么连接的,我跑完整个项目,但是添加ss或者ssr节点,点击连接按钮后,都没有任何反应
