### ISSUE TITLE
Implicit declaration of function 'OpenSSL_add_all_digests' is invalid in C99

### ISSUE THREAD

**Issue by XuCe** [ShadowsocksR-Live/iShadowsocksR#31]
xcode版本 10.1 以及 10.21
运行项目，utils下的Receipt.m 报错 
Implicit declaration of function 'OpenSSL_add_all_digests' is invalid in C99

**Comment by ssrlive** [comment]
我不理解你既然提出了前一 issue， 为什么又出现了这一条。

**Comment by XuCe** [comment]
因为 前面一个issue 打包的时候 我注释了这句话 我不知道是不是因为我注释了这个 引发的前面一个问题 所以我又提了一下

**Comment by XuCe** [comment]
好吧 这行注释了 对项目没有任何影响
