### ISSUE TITLE
规则不管用

### ISSUE THREAD

**Issue by ShuailongWang** [ShadowsocksR-Live/iShadowsocksR#32]
在国外，看爱奇艺视频， 打开视频发现视频显示地理限制无法观看，
配置中国服务器后，添加规则如下:
DomainMatch, iqiyi, Proxy

发现没有起作用，有什么解决的办法吗？

**Comment by ssrlive** [comment]
规则这块我也是稀里糊涂，抱歉。

**Comment by ShuailongWang** [comment]
好吧

**Comment by hexinyu1991** [comment]
我也遇到了这个问题  楼主解决了吗？

**Comment by madonya** [comment]
我这边设置Domain相关规则是有效的，设置GeoIp无效，有人遇到过吗
