### ISSUE TITLE
是否支持acl文件

### ISSUE THREAD

**Issue by sqzxcv** [ShadowsocksR-Live/iShadowsocksR#33]
我在local.c中增加bypass-china.acl配置文件, 发现没有效果, baidu.com还是不能直连, 是什么原因呢
```
int ssr_local_main_loop(const struct server_config *config, const char * _Nullable aclpath, void(*feedback_state)(struct ssr_local_state *state, void *p), void *p) {
    
    if (aclpath != NULL && strlen(aclpath) != 0) {
        acl = !init_acl(aclpath);
    }
```

**Comment by iRemark** [comment]
```
typedef struct {
    /*  Required  */
    char *remote_host;    // hostname or ip of remote server
    char *local_addr;     // local ip to bind
    char *method;         // encryption method
    char *password;       // password of remote server
    int remote_port;      // port number of remote server
    int local_port;       // port number of local server
    int timeout;          // connection timeout

    /*  Optional, set NULL if not valid   */
    char *acl;            // file path to acl
    char *log;            // file path to log
    int fast_open;        // enable tcp fast open
    int mode;             // enable udp relay
    int mtu;              // MTU of interface
    int mptcp;            // enable multipath TCP
    int verbose;          // verbose mode
} profile_t;
```
acl 通过上面的结构体传入的，调用接口如下：

ProxyManager.m 文件中的 _startShadowsocks 方法 把 acl 文件传入即可。
profile.acl = strdup([[PotatsoVPN sharedAPIAclUrl].path UTF8String]);

**Comment by NetFly-VPN** [comment]
> ```
> typedef struct {
>     /*  Required  */
>     char *remote_host;    // hostname or ip of remote server
>     char *local_addr;     // local ip to bind
>     char *method;         // encryption method
>     char *password;       // password of remote server
>     int remote_port;      // port number of remote server
>     int local_port;       // port number of local server
>     int timeout;          // connection timeout
> 
>     /*  Optional, set NULL if not valid   */
>     char *acl;            // file path to acl
>     char *log;            // file path to log
>     int fast_open;        // enable tcp fast open
>     int mode;             // enable udp relay
>     int mtu;              // MTU of interface
>     int mptcp;            // enable multipath TCP
>     int verbose;          // verbose mode
> } profile_t;
> ```
> 
> acl 通过上面的结构体传入的，调用接口如下：
> 
> ProxyManager.m 文件中的 _startShadowsocks 方法 把 acl 文件传入即可。
> profile.acl = strdup([[PotatsoVPN sharedAPIAclUrl].path UTF8String]);
上面的方法确定可行吗~~

**Comment by niancan** [comment]
shadowsocksr-libev 版本不对！！！ 还是自己移植吧! 他用的版本 感觉除了能正常connection 别的部分的问题都没有fix

**Comment by ssrlive** [comment]
@niancan 你们无耻盗用不声张也就算了, 你们无耻盗用以后还说盗用对象功能没让你爽. 你以为你是中共警察白日妓女不给钱还勒索人妓女两万? 你们有没有为这个项目哪怕做了一丁点贡献?

难怪 @icodesign 愤而删库, 就是你们这些数典忘祖都杂碎太多了.

要不老子也把库删了?
