### ISSUE TITLE
openssl-Implicit declaration of function 'OpenSSL_add_all_digests' is invalid in C99

### ISSUE THREAD

**Issue by magic1983** [ShadowsocksR-Live/iShadowsocksR#34]
Implicit declaration of function 'OpenSSL_add_all_digests' is invalid in C99
Implicit declaration of function 'EVP_cleanup' is invalid in C99

**Comment by penghongmao** [comment]
@magic1983 你好，问题解决了吗，我也遇到了这个问题，如果解决了帮忙指点一下，感谢大神

**Comment by penghongmao** [comment]
问题解决了吗，我也需要了这个问题，求指点

**Comment by rongshuizhou** [comment]
你好,请问你解决这个问题了么,求指点

**Comment by ssrlive** [comment]
一堆极端自私多蠢货加懒虫.
