### ISSUE TITLE
请问能尝试支持一下AEAD加密方式吗？

### ISSUE THREAD

**Issue by weqeo** [ShadowsocksR-Live/iShadowsocksR#35]
现在shadowsocks官网最推荐的加密方式已经变成了AEAD这种方式了：https://shadowsocks.org/en/spec/AEAD-Ciphers.html

Name | Alias | Key Size | Salt Size | Nonce Size | Tag Size
-- | -- | -- | -- | -- | --
AEAD_CHACHA20_POLY1305 | chacha20-ietf-poly1305 | 32 | 32 | 12 | 16
AEAD_AES_256_GCM | aes-256-gcm | 32 | 32 | 12 | 16
AEAD_AES_192_GCM | aes-192-gcm | 24 | 24 | 12 | 16
AEAD_AES_128_GCM | aes-128-gcm | 16 | 16 | 12 | 16

请问能尝试支持一下AEAD加密方式吗？谢谢～

**Comment by ssrlive** [comment]
没有计划。将来也不会支持。因为走了 SSRoT 以后，所有的混淆、加密都是累赘的无用功。

**Comment by weqeo** [comment]
> 没有计划。将来也不会支持。因为走了 SSRoT 以后，所有的混淆、加密都是多余的，是累赘、无用的。

好的，那请问如果我个人想要尝试支持AEAD的加密方式的话，该如何入手呢？我希望能尝试一下，感谢🙏

**Comment by ssrlive** [comment]
可以看看 encrypt.c 文件，看看怎麼著手。

**Comment by weqeo** [comment]
> 可以看看 encrypt.c 文件，看看怎麼著手。

好的，感谢

**Comment by ssrlive** [comment]
已经支持 AEAD 加密。
