### ISSUE TITLE
连接微信、telegram、WhatsApp不稳定。

### ISSUE THREAD

**Issue by pang-w** [ShadowsocksR-Live/iShadowsocksR#45]
偶尔能连接上，偶尔连接不上这些软件，很奇怪，线路没有问题，另一台安卓设备一直在连接。

打印日志，发现如下错误。

![image](https://user-images.githubusercontent.com/5512719/75096420-67bea400-55da-11ea-80e2-d5671571ef34.png)
![image](https://user-images.githubusercontent.com/5512719/75096423-6ee5b200-55da-11ea-89e4-3458110a20f9.png)

NFO(tun2socks): 00003 (157.240.15.54:5222 192.0.2.1:52505): client_recv_func client received (4096)
INFO(tun2socks): 00003 (157.240.15.54:5222 192.0.2.1:52505): client closed

DEBUG(BSocksClient): received reply rest
DEBUG(BReactor): Got already expired timers

**Comment by pang-w** [comment]
经常有以上错误，完全排除线路问题。~

**Comment by mtt2020** [comment]
请问如何解决的
