### ISSUE TITLE
Geoip 设置无效

### ISSUE THREAD

**Issue by madonya** [ShadowsocksR-Live/iShadowsocksR#46]
如题，设置GeoIp cn DIRECT无效，其他的action也无效，求大佬回答一下

**Comment by ssrlive** [comment]
分流這一塊沒弄。 靠你自己了。

**Comment by madonya** [comment]
> 分流這一塊沒弄。 靠你自己了。
好吧，我研究研究

**Comment by madonya** [comment]
> 分流這一塊沒弄。 靠你自己了。

好吧，我研究研究

**Comment by madonya** [comment]
> 分流這一塊沒弄。 靠你自己了。

大佬可以简单讲一下这块的代码在哪里吗，感谢

**Comment by ssrlive** [comment]
https://github.com/ShadowsocksR-Live/iShadowsocksR/blob/3f45a3904206773025425e3bd6dc23771ac7a9e8/Library/ShadowPath/ShadowPath/Privoxy/filters.c#L2689

**Comment by madonya** [comment]
> https://github.com/ShadowsocksR-Live/iShadowsocksR/blob/3f45a3904206773025425e3bd6dc23771ac7a9e8/Library/ShadowPath/ShadowPath/Privoxy/filters.c#L2689

谢谢大佬！

**Comment by madonya** [comment]
> https://github.com/ShadowsocksR-Live/iShadowsocksR/blob/3f45a3904206773025425e3bd6dc23771ac7a9e8/Library/ShadowPath/ShadowPath/Privoxy/filters.c#L2689-L2715

看了半天，改不动啊，不知道从哪下手。
forward_ip 里获取到的 action一直都是 NULL，是要重新构造一个action吗？但是我自己在forward_ip_routing里构造了一个（不知道是否有效），然后不起作用。
请大佬再指点一二，我这块的基础不是很好 O.o
感激不尽

**Comment by madonya** [comment]
> https://github.com/ShadowsocksR-Live/iShadowsocksR/blob/3f45a3904206773025425e3bd6dc23771ac7a9e8/Library/ShadowPath/ShadowPath/Privoxy/filters.c#L2689-L2715

我大概找到原因了，在这段代码里获取到的值 entry_data.utf8_string 一直都是GB开头的，所以走不到后边的 if 语句。但是这里奇怪的是无论打开哪个国家的网站获取到的都是错误的以GB开头的值，请问这是 libmaxminddb 的bug吗

**Comment by thomashooo** [comment]
搞定了吗，GEOIP的设置？

**Comment by madonya** [comment]
> 搞定了吗，GEOIP的设置？

项目搁置了，疑似路由器的问题，建议换个路由器试试
