### ISSUE TITLE
EXC_BAD_ACCESS crash

### ISSUE THREAD

**Issue by madonya** [ShadowsocksR-Live/iShadowsocksR#47]
![1585036292051](https://user-images.githubusercontent.com/9879259/77401163-648c2300-6de7-11ea-9b46-36232f56fa6d.jpg)

使用爱奇艺观看视频会触发崩溃
有人遇到过吗

**Comment by ssrlive** [comment]
试过. 没有崩溃.

**Comment by magangke** [comment]
#51 我的也是，刚发现已经有Issues

**Comment by 86speed** [comment]
> #51 我的也是，刚发现已经有Issues

爱奇艺 拖动快进 多拖几次就会闪退，连接会自动断开，你们怎么解决？

**Comment by madonya** [comment]
这里是有一个存放IP和端口的字典（大概，这里记不大清了）是线程不安全的，你们可以试试解解看

**Comment by 86speed** [comment]
> 这里是有一个存放IP和端口的字典（大概，这里记不大清了）是线程不安全的，你们可以试试解解看

好的，我试试，内存溢出15mb 你解决了吗

**Comment by madonya** [comment]
> > 这里是有一个存放IP和端口的字典（大概，这里记不大清了）是线程不安全的，你们可以试试解解看
> 
> 好的，我试试，内存溢出15mb 你解决了吗

使用attach调试的时候内存占用会增加，应该是这个原因导致了你内存溢出

**Comment by 86speed** [comment]
> > > 这里是有一个存放IP和端口的字典（大概，这里记不大清了）是线程不安全的，你们可以试试解解看
> > 
> > 
> > 好的，我试试，内存溢出15mb 你解决了吗
> 
> 使用attach调试的时候内存占用会增加，应该是这个原因导致了你内存溢出

你那边测试正常？我不在调试的情况下，我使用speedtest 测速，每次测到上传的速度就会超15mb，然后被系统kill

**Comment by ssrlive** [comment]
15M崩溃的问题可能无解， #58

**Comment by 86speed** [comment]
> 15M崩溃的问题可能无解， #58

但我用其他软件，使用同样测试，可以正常。不知道怎么处理的。我看有一个方案 把缓冲区改成背压的模式。这样可能速度上略有下降，但内存不会立马爆了

**Comment by ssrlive** [comment]
buffer_t 的设计当时考虑的就是怎么方便加密算法的顺利执行，可能有点浪费，每次都是2K起跳，估计这里有点奢侈，目前没时间专门针对iOS做调整。改成现在这样也是掉了无数的坑以后的结果。

**Comment by 86speed** [comment]
> buffer_t 的设计当时考虑的就是怎么方便加密算法的顺利执行，可能有点浪费，每次都是2K起跳，估计这里有点奢侈，目前没时间专门针对iOS做调整。改成现在这样也是掉了无数的坑以后的结果。

嗯，我研究研究。大佬有时间可以优化优化，这个问题困扰了好久。有偿支持也行

**Comment by ssrlive** [comment]
不能收钱。中共克格勃会找上门的。

**Comment by 86speed** [comment]
> 不能收钱。中共克格勃会找上门的。

哦哦明白，捐赠😃

**Comment by 86speed** [comment]
> 这里是有一个存放IP和端口的字典（大概，这里记不大清了）是线程不安全的，你们可以试试解解看

换成线程安全的dic,测试了 目前没有发现异常 ，感谢

**Comment by ssrlive** [comment]
提个 patch 吧。

>

**Comment by 86speed** [comment]
> 提个 patch 吧。
> […](#)

没问题

**Comment by ssrlive** [comment]
@86speed 你是说是这个变量没加锁?
https://github.com/ShadowsocksR-Live/iShadowsocksR/blob/77193d82e8946a6a98f1217af02b3f1cdc577369/PacketProcessor/TunnelInterface.m#L26
