### ISSUE TITLE
请问这个项目支持SSRoT特性吗?

### ISSUE THREAD

**Issue by whatsbug** [ShadowsocksR-Live/iShadowsocksR#48]
RT

**Comment by ssrlive** [comment]
目前有个关键问题没解决。目前不支持。

**Comment by whatsbug** [comment]
收到。

**Comment by godlikejoke** [comment]
你好大佬，我看到你最新有更新代码SSRoT特性部分，请问该项目是支持了SSRoT特性吗

**Comment by ssrlive** [comment]
已经支持.  https://github.com/ShadowsocksR-Live/shadowsocksr-native/issues/68#issuecomment-629913031
