### ISSUE TITLE
Build 过程中 API.swift 文件异常

### ISSUE THREAD

**Issue by wowzql** [ShadowsocksR-Live/iShadowsocksR#5]
在进行Build过程中，在API.swift中提示两处异常。小白有点不知道怎么办，求大佬帮忙看下可以嘛~ 感激不尽。

/GitHub/iShadowsocksR2/Potatso/Core/API.swift:65:12: Initializer for conditional binding must have Optional type, not '[Rule]'

/GitHub/iShadowsocksR2/Potatso/Core/API.swift:255:20: Initializer for conditional binding must have Optional type, not '[T]'

另外之前在build时 Cartography 也有异常，手动修改了pod中的版本后就没有提示了。。。 Xcode版本 9.3 9.2都有试过了~ 谢谢

**Comment by ssrlive** [comment]
我对 swift 也是外行，每次版本Xcode升级也很痛苦。你把报错的那两坨代码注释掉就可以了。

**Comment by wowzql** [comment]
大佬你回复的好快...正在尝试注释掉这段

**Comment by wowzql** [comment]
又遇到了新的问题，好头痛

**Comment by ssrlive** [comment]
還是註釋掉.

**Comment by youngsing** [comment]
还没跑过代码，仅仅处理了下编译错误，所以仅供参考：
```swift
if let parsedObject = Mapper<Rule>().mapArray(JSONObject: rulesJSON) {
        rules.append(contentsOf: parsedObject)
}
```
或者使用下面的方式初始化
```swift
let rules = Mapper<Rule>().mapArray(JSONArray: rulesJSON as! [[String: Any]])
```
至于原因，编译器给的提示其实很准确，仔细看下就明白了。

**Comment by ssrlive** [comment]
@youngsing 改完了.
