### ISSUE TITLE
target闪退：unrecognized selector sent to instance和EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by magangke** [ShadowsocksR-Live/iShadowsocksR#51]
配置ss后，打开代理。
播放爱奇艺等视频客户端时候，（播放一会儿后）会出现unrecognized selector sent to instance

![截屏2020-05-30 下午6 25 30](https://user-images.githubusercontent.com/66164543/83326102-d54a3280-a2a3-11ea-85c7-84c152dc2c17.jpg)
![截屏2020-05-30 下午6 25 02](https://user-images.githubusercontent.com/66164543/83326106-d713f600-a2a3-11ea-9e66-16108c6ba22f.jpg)

有时候也会出现EXC_BAD_ACCESS

![截屏2020-05-30 下午6 35 01](https://user-images.githubusercontent.com/66164543/83326183-5275a780-a2a4-11ea-92b8-f5a48841c650.jpg)
EXC_BAD_ACCESS出现的位置有时候在方法头部，有时候在尾部，有时候在中间

每次都会出现上面两个问题之一

**Comment by 86speed** [comment]
> 配置ss后，打开代理。
> 播放爱奇艺等视频客户端时候，（播放一会儿后）会出现unrecognized selector sent to instance
> 
> ![截屏2020-05-30 下午6 25 30](https://user-images.githubusercontent.com/66164543/83326102-d54a3280-a2a3-11ea-85c7-84c152dc2c17.jpg)
> ![截屏2020-05-30 下午6 25 02](https://user-images.githubusercontent.com/66164543/83326106-d713f600-a2a3-11ea-9e66-16108c6ba22f.jpg)
> 
> 有时候也会出现EXC_BAD_ACCESS
> 
> ![截屏2020-05-30 下午6 35 01](https://user-images.githubusercontent.com/66164543/83326183-5275a780-a2a4-11ea-92b8-f5a48841c650.jpg)
> EXC_BAD_ACCESS出现的位置有时候在方法头部，有时候在尾部，有时候在中间
> 
> 每次都会出现上面两个问题之一


爱奇艺 拖动快进 多拖几次就会闪退，连接会自动断开，你们怎么解决？
