### ISSUE TITLE
SSR可以连接成功，但是启动SSROT就无法访问

### ISSUE THREAD

**Issue by godlikejoke** [ShadowsocksR-Live/iShadowsocksR#54]
请教个问题大佬，首先我是down的最新代码，SSR可以连接成功，但是启动SSROT就无法访问。
服务器上nginx我看到的访问日志是没有数据过来的。

![image](https://user-images.githubusercontent.com/11766916/89176674-8e86fa80-d5bc-11ea-86bc-6d51ebfe2b65.png)
上面图片红色部分是启动SSROT访问的，数据没有过来，下面部分是我用vmess访问的（可以成功，nginx应该没有配置错误）。

ssrot配置图：
![image](https://user-images.githubusercontent.com/11766916/89177312-bb87dd00-d5bd-11ea-8337-813e921c015c.png)

nginx配置图
![image](https://user-images.githubusercontent.com/11766916/89177399-fb4ec480-d5bd-11ea-9203-f9d614d55db6.png)

ssr配置服务监听的是10025
![image](https://user-images.githubusercontent.com/11766916/89177776-bd05d500-d5be-11ea-80d1-4e51c91e844b.png)

请问是我哪里弄错了吗,直接是用SSR倒是可以连接上并且有数据返回。

**Comment by ssrlive** [comment]
over_tls_settings 没设置正确.

**Comment by ssrlive** [comment]
z 这些数据服务器端会读取验证的, 有任何差池都会拒绝连接的.

**Comment by ssrlive** [comment]
自动安装以后的配置文件 自己 cat 打印出来自己看看就知道哪里不对了.

**Comment by godlikejoke** [comment]
是这样吗
"over_tls_settings": {
        "enable": ture,
        "server_domain": "我的域名",
        "path": "/ssrot/",
        "root_cert_file": "我的cert证书地址"
    }

**Comment by ssrlive** [comment]
是

**Comment by godlikejoke** [comment]
我看到网上有些人没有配置root_cert_file 选项，这个会有什么影响吗

**Comment by ssrlive** [comment]
这个是针对客户端的, 目前没有使用

**Comment by ssrlive** [comment]
留待将来用于客户端的验证用的.

**Comment by godlikejoke** [comment]
非常感谢，最后一个问题（不要嫌我啰嗦哈），ssrot使用websocks+tls 和 v2ray的websocks+tls  原理是不是一样的

**Comment by ssrlive** [comment]
是一样的, Wiki 里把所有关键点都说白了. 但ssrot 是 纯 c 实现的, 快一个数量级.
