### ISSUE TITLE
运行项目会导致苹果账号被封

### ISSUE THREAD

**Issue by godlikejoke** [ShadowsocksR-Live/iShadowsocksR#55]
首先你好大佬，
我发现我运行这个项目的代码会导致我的苹果账号被封。
我很确定代码只有在我的电脑和手机上运行。
而且我收到了苹果的邮件说我违规，可是我只有在我电脑在我电脑上只运行这个项目而已。

是不是这个项目有上传个人开发者账号到苹果，还是项目有版权呢？

**Comment by ssrlive** [comment]
第一次听到这个消息。你改了 app ID 了吗？不改编译不过的。

**Comment by godlikejoke** [comment]
我改过id了，是我自己的开发者账号，网上查了一下出现这种情况的一般都是账号有明显的侵权行为或涉及违规内容。
是不是因为是vpn，所以导致的。

**Comment by ssrlive** [comment]
没上传商店。不应该出现警告。

**Comment by godlikejoke** [comment]
因为我的账号开发运行这个vpn，这是我唯一能想到的原因。
又或者是代码里是否有启动的时候上传违规资料等呢

**Comment by godlikejoke** [comment]
然后我看了下启动app的时候有2个类UrlHandler和DataInitializer，这2个类是否有同步一些信息到苹果呢

**Comment by ssrlive** [comment]
没这些代码片段。开源的。不放心可以自行查看。

**Comment by ssrlive** [comment]
这些是最原始的作者写的。我没细究。我已经砍掉很多花里胡哨的代码了。

**Comment by ssrlive** [comment]
要不把 iCloud 相关的代码也砍掉，不让沾染 云上贵州， 对用户更安全点。

**Comment by ssrlive** [comment]
我没时间做这些，你如果做了，提交个 PR 吧。

**Comment by godlikejoke** [comment]
iCloud 相关的代码位置在哪里

**Comment by ssrlive** [comment]
你找一下吧。我很久不在mac机上工作了。

**Comment by godlikejoke** [comment]
源作者iCloud 的作用是用来做什么的？

**Comment by ssrlive** [comment]
保存各种节点配置的。方便手机之间同步。

**Comment by BJGX** [comment]
大佬 我的苹果账号也被封了

**Comment by ssrlive** [comment]
太神奇了，你是接到警告还是账号被封？能把信件内容贴出来吗？
