### ISSUE TITLE
Error building:  switch must be exhaustive 

### ISSUE THREAD

**Issue by alizahedi94** [ShadowsocksR-Live/iShadowsocksR#56]
Followed all instructions to build and I get an error. 

How do I fix issue?  Thanks 

![5265BE7F-DA2D-420A-AF9D-8C7FDAD9EF89](https://user-images.githubusercontent.com/71351300/93720024-6fd0c900-fb54-11ea-886c-013e97eda3d5.jpeg)

**Comment by ssrlive** [comment]
https://stackoverflow.com/a/26686733
