### ISSUE TITLE
请问 V2Ray-Plugin 怎么配置

### ISSUE THREAD

**Issue by BJGX** [ShadowsocksR-Live/iShadowsocksR#57]
![截屏2020-09-29 下午2 04 43](https://user-images.githubusercontent.com/23720906/94519037-c7f68200-025c-11eb-84bd-9218736ea122.png)
我的服务器
![Screen Shot 2020-09-29 at 1 55 14 PM](https://user-images.githubusercontent.com/23720906/94519436-10ae3b00-025d-11eb-9047-62e6b736c680.png)
我怎么在编辑代理里面配置V2Ray-Plugin 
求大佬解答

**Comment by ssrlive** [comment]
你找错地方了。
