### ISSUE TITLE
EXC_RESOURCE -> PacketTunnel[7988] exceeded mem limit: ActiveHard 15 MB (fatal)

### ISSUE THREAD

**Issue by 86speed** [ShadowsocksR-Live/iShadowsocksR#58]
使用Instruments检查是没有内存泄漏的，但ios使用uutest.cn测速（软件下载地址:uuspeed.uutest.cn），测试到上传速度的时候，会被系统kill掉，提示内存超过15MB
EXC_RESOURCE -> PacketTunnel[7988] exceeded mem limit: ActiveHard 15 MB (fatal)
 
![image](https://user-images.githubusercontent.com/67633762/94646910-ea9e9e80-0321-11eb-9b8c-43f940c7d3af.png)
libuv、tun2socks-iOS、ssrbuffer.c
不确定从哪块入手、对c不熟
是不是可以把ssrbuffer 替换成 circular buffer

**Comment by ssrlive** [comment]
如果短时间发起大量连接,libuv的事件循环来不及处理,就会造成内存消耗,我在Windows机器上几乎每天挂着代理,开着视频,连续运行几天都没事.

**Comment by 86speed** [comment]
> 几乎



> 如果短时间发起大量连接,libuv的事件循环来不及处理,就会造成内存消耗,我在Windows机器上几乎每天挂着代理,开着视频,连续运行几天都没事.

有没什么解决思路？或相关资料？

**Comment by ssrlive** [comment]
你先看看那个测试软件短时间发起了多少连接，再进一步研究，如何连接很少，那就是 SSR-N 的问题，如果很多，那就没什么好的办法处理这个 issue 了。

**Comment by 86speed** [comment]
连接数不多 还没有看视频多，看视频内存一直再8MB左右
![image](https://user-images.githubusercontent.com/67633762/94653348-0740d380-032e-11eb-8d33-ac58337ea9f5.png)


![image](https://user-images.githubusercontent.com/67633762/94653316-f5f7c700-032d-11eb-9e49-4e791ec2b5ed.png)

**Comment by ssrlive** [comment]
那就不清楚为什么会造成数据积压了。

**Comment by 86speed** [comment]
测速的时候查看instruments 开辟了2w+地址
![image](https://user-images.githubusercontent.com/67633762/94661518-bdf68100-0339-11eb-9c95-c7dc7f848caf.png)

**Comment by ssrlive** [comment]
这种极限施压的情况估计是iOS不欢迎的，觉得还是不折腾了。

**Comment by ssrlive** [comment]
总觉得苹果应该给用户一个选择，特定某个应用的后台可以使用最大的内存数量，让用户决定。世界就和平了。
