### ISSUE TITLE
有没有可直接编译的工程啊

### ISSUE THREAD

**Issue by DockLle** [ShadowsocksR-Live/iShadowsocksR#59]
放网盘给下一下啊老哥，pod realm 过不去，心塞

**Comment by ssrlive** [comment]
这没办法，原作者爱死垃圾 realm 了，你能指望有人彻底改写工程，去掉 realm 吗？

免费享用代码的人99%的人不是能力不够就是极其鸡贼，想找我这样的实诚人万不及一。

自己想办法吧。没空做这个。

**Comment by ssrlive** [comment]
https://github.com/ShadowsocksR-Live/iShadowsocksR#tips

**Comment by DockLle** [comment]
这样吧老哥，我付费给你拿直接可编译的工程，我自己翻墙用，加个微信吧

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ssrlive <notifications@github.com&gt;
发送时间: 2020年10月31日 13:55
收件人: ShadowsocksR-Live/iShadowsocksR <iShadowsocksR@noreply.github.com&gt;
抄送: DockLle <1024799300@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[ShadowsocksR-Live/iShadowsocksR] 有没有可直接编译的工程啊 (#59)





 
这没办法，原作者爱死垃圾 realm 了，你能指望有人彻底改写工程，去掉 realm 吗？
 
免费享用代码的人99%的人不是能力不够就是极其鸡贼，想找我这样的实诚人万不及一。
 
自己想办法吧。没空做这个。

**Comment by ssrlive** [comment]
那我怀疑你是中共盖世太保克格勃来钓鱼的。自己弄吧！

**Comment by DockLle** [comment]
算了算了，老哥你是真的狠，你这没啥影响力，盖世太保没空吊你😂



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ssrlive <notifications@github.com&gt;
发送时间: 2020年10月31日 14:01
收件人: ShadowsocksR-Live/iShadowsocksR <iShadowsocksR@noreply.github.com&gt;
抄送: DockLle <1024799300@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[ShadowsocksR-Live/iShadowsocksR] 有没有可直接编译的工程啊 (#59)





 
那我怀疑你是中共盖世太保克格勃来钓鱼的。自己弄吧！

**Comment by ssrlive** [comment]
这也直接证明你属于那99%的人了。

**Comment by ssrlive** [comment]
最后再帮你一把：在VPS的linux上安装 git 和 cocoapods 软件，然后在vps上拉取所有源代码，然后 zip 打包，然后用 web 服务器下载下来这个 zip 包。
