### ISSUE TITLE
SSRoT 内存溢出了

### ISSUE THREAD

**Issue by JohnSnooow** [ShadowsocksR-Live/iShadowsocksR#61]
大佬，开启ot 之后，VPN本身可以连接成功，内存占用大概在6、7M，然后随意打开一个网页，PacketTunnel内存涨到15M 就崩溃了。崩溃的位置不太固定。 不开ot是可以的使用的。 手机是 XS，14.2
![image](https://user-images.githubusercontent.com/52422130/100082971-73960a00-2e7b-11eb-9a03-003ba6dc4485.png)
![image](https://user-images.githubusercontent.com/52422130/100083027-827cbc80-2e7b-11eb-8a0c-9ecb85f4a4ab.png)
![image](https://user-images.githubusercontent.com/52422130/100083262-c8d21b80-2e7b-11eb-8ca4-043306bae9c6.png)

**Comment by ssrlive** [comment]
哪个网页？

**Comment by JohnSnooow** [comment]
百度 google 什么的，都会崩

**Comment by ssrlive** [comment]
真他妈要命，也许以后会用 rust 重写一遍。现在只能这样了。

**Comment by JohnSnooow** [comment]
好的 谢谢大佬。
