### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by SonnyDeng** [ShadowsocksR-Live/iShadowsocksR#65]
![image](https://user-images.githubusercontent.com/7664459/142584741-277e4a72-6aa0-4b92-a1c0-1da367f20661.png)

大佬知道这个编译报错怎么解决吗？我的是ios15  xcode13

**Comment by ssrlive** [comment]
不知道，沒有這些軟硬件環境。

**Comment by ZIYOCHIRO** [comment]
由于升级Xcode13之后的一系列关于Swift的报错：
CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
Command CompileSwiftSources failed with a nonzero exit code
type ‘struct icmp6_hdr’ has incompatible definitions in different translation units

解决：
1.swift version指定为4.0
2.Development target从9.0改为11.0
3.工程里使用的struct icmp6_hdr应该是与系统库里的名字冲突了， icmp6_hdr全局替换为icmp6_ex_hdr

**Comment by ssrlive** [comment]
希望你能提交一个 PR。干净的PR。

**Comment by ssrlive** [comment]
不劳各位了，我自己已经搞完，而且支持 SS 和 AEAD。哪个发送给我一个编译好的 ipa 文件？被走狗警察找上的概率你们比我低一点。
