### ISSUE TITLE
About Cycle inside CallbackURLKit; building could produce unreliable results

### ISSUE THREAD

**Issue by lls275** [ShadowsocksR-Live/iShadowsocksR#68]
When I build the project, I find that the Cycle inside CallbackURLKit; building could produce unreliable results. error will appear. How can I fix it?

```
Cycle inside CallbackURLKit; building could produce unreliable results. This usually can be resolved by moving the target's Headers build phase before Compile Sources.
Cycle details:
→ Target 'CallbackURLKit' has link command with output '/Users/jz/Library/Developer/Xcode/DerivedData/iShadowsocksR-acvpbhqcwpoufuaguoictgwlbiuc/Build/Products/Debug-iphoneos/CallbackURLKit.framework/CallbackURLKit'
○ Target 'CallbackURLKit' has compile command with input '/Users/jz/Library/Developer/Xcode/DerivedData/iShadowsocksR-acvpbhqcwpoufuaguoictgwlbiuc/Build/Intermediates.noindex/CallbackURLKit.build/Debug-iphoneos/CallbackURLKit.build/DerivedSources/CallbackURLKit_vers.c'
○ Target 'CallbackURLKit' has compile command for Swift source files
○ Target 'CallbackURLKit' has copy command from '/Users/jz/Desktop/iShadowsocksR/Library/CallbackURLKit/Xcode/iOS/CallbackURLKit.h' to '/Users/jz/Library/Developer/Xcode/DerivedData/iShadowsocksR-acvpbhqcwpoufuaguoictgwlbiuc/Build/Products/Debug-iphoneos/CallbackURLKit.framework/Headers/CallbackURLKit.h'


Raw dependency cycle trace:

target:  ->

node: <all> ->

command: <all> ->

node: /Users/jz/Library/Developer/Xcode/DerivedData/iShadowsocksR-acvpbhqcwpoufuaguoictgwlbiuc/Build/Products/Debug-iphoneos/CallbackURLKit.framework/CallbackURLKit ->

command: target-CallbackURLKit-cabbd167fcd07023ca79fb7460ac722decb0589ae08e4a27c16de552d16baa80-:Debug:Ld /Users/jz/Library/Developer/Xcode/DerivedData/iShadowsocksR-acvpbhqcwpoufuaguoictgwlbiuc/Build/Products/Debug-iphoneos/CallbackURLKit.framework/CallbackURLKit normal ->

CYCLE POINT ->

node: /Users/jz/Library/Developer/Xcode/DerivedData/iShadowsocksR-acvpbhqcwpoufuaguoictgwlbiuc/Build/Intermediates.noindex/CallbackURLKit.build/Debug-iphoneos/CallbackURLKit.build/Objects-normal/arm64/CallbackURLKit_vers.o ->

command: target-CallbackURLKit-cabbd167fcd07023ca79fb7460ac722decb0589ae08e4a27c16de552d16baa80-:Debug:CompileC /Users/jz/Library/Developer/Xcode/DerivedData/iShadowsocksR-acvpbhqcwpoufuaguoictgwlbiuc/Build/Intermediates.noindex/CallbackURLKit.build/Debug-iphoneos/CallbackURLKit.build/Objects-normal/arm64/CallbackURLKit_vers.o /Users/jz/Library/Developer/Xcode/DerivedData/iShadowsocksR-acvpbhqcwpoufuaguoictgwlbiuc/Build/Intermediates.noindex/CallbackURLKit.build/Debug-iphoneos/CallbackURLKit.build/DerivedSources/CallbackURLKit_vers.c normal arm64 c com.apple.compilers.llvm.clang.1_0.compiler ->

node: <target-CallbackURLKit-cabbd167fcd07023ca79fb7460ac722decb0589ae08e4a27c16de552d16baa80--generated-headers> ->

command: Gate target-CallbackURLKit-cabbd167fcd07023ca79fb7460ac722decb0589ae08e4a27c16de552d16baa80--generated-headers ->

node: /Users/jz/Library/Developer/Xcode/DerivedData/iShadowsocksR-acvpbhqcwpoufuaguoictgwlbiuc/Build/Intermediates.noindex/CallbackURLKit.build/Debug-iphoneos/CallbackURLKit.build/Objects-normal/arm64/Client.o ->

command: target-CallbackURLKit-cabbd167fcd07023ca79fb7460ac722decb0589ae08e4a27c16de552d16baa80-:Debug:CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler ->

node: /Users/jz/Library/Developer/Xcode/DerivedData/iShadowsocksR-acvpbhqcwpoufuaguoictgwlbiuc/Build/Products/Debug-iphoneos/CallbackURLKit.framework/Headers/CallbackURLKit.h ->

command: target-CallbackURLKit-cabbd167fcd07023ca79fb7460ac722decb0589ae08e4a27c16de552d16baa80-:Debug:CpHeader /Users/jz/Library/Developer/Xcode/DerivedData/iShadowsocksR-acvpbhqcwpoufuaguoictgwlbiuc/Build/Products/Debug-iphoneos/CallbackURLKit.framework/Headers/CallbackURLKit.h /Users/jz/Desktop/iShadowsocksR/Library/CallbackURLKit/Xcode/iOS/CallbackURLKit.h ->

node: <target-CallbackURLKit-cabbd167fcd07023ca79fb7460ac722decb0589ae08e4a27c16de552d16baa80--phase0-compile-sources> ->

command: Gate target-CallbackURLKit-cabbd167fcd07023ca79fb7460ac722decb0589ae08e4a27c16de552d16baa80--phase0-compile-sources ->

node: /Users/jz/Library/Developer/Xcode/DerivedData/iShadowsocksR-acvpbhqcwpoufuaguoictgwlbiuc/Build/Intermediates.noindex/CallbackURLKit.build/Debug-iphoneos/CallbackURLKit.build/Objects-normal/arm64/CallbackURLKit_vers.o
```

**Comment by ssrlive** [comment]
I don't know what happenned to you. But I can ensure you have changed the project settings. just checkout source code from beginning and try it  again.

**Comment by lls275** [comment]
> I don't know what happenned to you. But I can ensure you have changed the project settings. just checkout source code from beginning and try it again.

May I ask the author, which xcode version are you using now to compile?

**Comment by ssrlive** [comment]
![Screen Shot 2022-04-21 at 16 53 03](https://user-images.githubusercontent.com/30760636/164418335-be520960-3a2c-4c79-b7b0-6051d452a511.png)

**Comment by lls275** [comment]
> ![Screen Shot 2022-04-21 at 16 53 03](https://user-images.githubusercontent.com/30760636/164418335-be520960-3a2c-4c79-b7b0-6051d452a511.png)

too weird! I also use this version to compile, but the above error occurs. I compiled according to the following steps, but the error still occurs.I am using macos on the x86 platform. 
```
git clone --recurse-submodules https://github.com/ShadowsocksR-Live/iShadowsocksR.git
cd iShadowsocksR
sudo gem install cocoapods
pod install                                # pull down dependencies into our project
```

Can you tell me the detailed steps? There is a bug that occurs https://github.com/ShadowsocksR-Live/iShadowsocksR/issues/65#issue-1058240829

**Comment by lls275** [comment]
What is your current Macos system version?

**Comment by ssrlive** [comment]
![Screen Shot 2022-04-21 at 17 03 21](https://user-images.githubusercontent.com/30760636/164420982-e95c96ec-982a-49f1-ba30-af49c117280a.png)

**Comment by paopao517** [comment]
> When I build the project, I find that the Cycle inside CallbackURLKit; building could produce unreliable results. error will appear. How can I fix it?
> 
> ```
> Cycle inside CallbackURLKit; building could produce unreliable results. This usually can be resolved by moving the target's Headers build phase before Compile Sources.
> Cycle details:
> → Target 'CallbackURLKit' has link command with output '/Users/jz/Library/Developer/Xcode/DerivedData/iShadowsocksR-acvpbhqcwpoufuaguoictgwlbiuc/Build/Products/Debug-iphoneos/CallbackURLKit.framework/CallbackURLKit'
> ○ Target 'CallbackURLKit' has compile command with input '/Users/jz/Library/Developer/Xcode/DerivedData/iShadowsocksR-acvpbhqcwpoufuaguoictgwlbiuc/Build/Intermediates.noindex/CallbackURLKit.build/Debug-iphoneos/CallbackURLKit.build/DerivedSources/CallbackURLKit_vers.c'
> ○ Target 'CallbackURLKit' has compile command for Swift source files
> ○ Target 'CallbackURLKit' has copy command from '/Users/jz/Desktop/iShadowsocksR/Library/CallbackURLKit/Xcode/iOS/CallbackURLKit.h' to '/Users/jz/Library/Developer/Xcode/DerivedData/iShadowsocksR-acvpbhqcwpoufuaguoictgwlbiuc/Build/Products/Debug-iphoneos/CallbackURLKit.framework/Headers/CallbackURLKit.h'
> 
> 
> Raw dependency cycle trace:
> 
> target:  ->
> 
> node: <all> ->
> 
> command: <all> ->
> 
> node: /Users/jz/Library/Developer/Xcode/DerivedData/iShadowsocksR-acvpbhqcwpoufuaguoictgwlbiuc/Build/Products/Debug-iphoneos/CallbackURLKit.framework/CallbackURLKit ->
> 
> command: target-CallbackURLKit-cabbd167fcd07023ca79fb7460ac722decb0589ae08e4a27c16de552d16baa80-:Debug:Ld /Users/jz/Library/Developer/Xcode/DerivedData/iShadowsocksR-acvpbhqcwpoufuaguoictgwlbiuc/Build/Products/Debug-iphoneos/CallbackURLKit.framework/CallbackURLKit normal ->
> 
> CYCLE POINT ->
> 
> node: /Users/jz/Library/Developer/Xcode/DerivedData/iShadowsocksR-acvpbhqcwpoufuaguoictgwlbiuc/Build/Intermediates.noindex/CallbackURLKit.build/Debug-iphoneos/CallbackURLKit.build/Objects-normal/arm64/CallbackURLKit_vers.o ->
> 
> command: target-CallbackURLKit-cabbd167fcd07023ca79fb7460ac722decb0589ae08e4a27c16de552d16baa80-:Debug:CompileC /Users/jz/Library/Developer/Xcode/DerivedData/iShadowsocksR-acvpbhqcwpoufuaguoictgwlbiuc/Build/Intermediates.noindex/CallbackURLKit.build/Debug-iphoneos/CallbackURLKit.build/Objects-normal/arm64/CallbackURLKit_vers.o /Users/jz/Library/Developer/Xcode/DerivedData/iShadowsocksR-acvpbhqcwpoufuaguoictgwlbiuc/Build/Intermediates.noindex/CallbackURLKit.build/Debug-iphoneos/CallbackURLKit.build/DerivedSources/CallbackURLKit_vers.c normal arm64 c com.apple.compilers.llvm.clang.1_0.compiler ->
> 
> node: <target-CallbackURLKit-cabbd167fcd07023ca79fb7460ac722decb0589ae08e4a27c16de552d16baa80--generated-headers> ->
> 
> command: Gate target-CallbackURLKit-cabbd167fcd07023ca79fb7460ac722decb0589ae08e4a27c16de552d16baa80--generated-headers ->
> 
> node: /Users/jz/Library/Developer/Xcode/DerivedData/iShadowsocksR-acvpbhqcwpoufuaguoictgwlbiuc/Build/Intermediates.noindex/CallbackURLKit.build/Debug-iphoneos/CallbackURLKit.build/Objects-normal/arm64/Client.o ->
> 
> command: target-CallbackURLKit-cabbd167fcd07023ca79fb7460ac722decb0589ae08e4a27c16de552d16baa80-:Debug:CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler ->
> 
> node: /Users/jz/Library/Developer/Xcode/DerivedData/iShadowsocksR-acvpbhqcwpoufuaguoictgwlbiuc/Build/Products/Debug-iphoneos/CallbackURLKit.framework/Headers/CallbackURLKit.h ->
> 
> command: target-CallbackURLKit-cabbd167fcd07023ca79fb7460ac722decb0589ae08e4a27c16de552d16baa80-:Debug:CpHeader /Users/jz/Library/Developer/Xcode/DerivedData/iShadowsocksR-acvpbhqcwpoufuaguoictgwlbiuc/Build/Products/Debug-iphoneos/CallbackURLKit.framework/Headers/CallbackURLKit.h /Users/jz/Desktop/iShadowsocksR/Library/CallbackURLKit/Xcode/iOS/CallbackURLKit.h ->
> 
> node: <target-CallbackURLKit-cabbd167fcd07023ca79fb7460ac722decb0589ae08e4a27c16de552d16baa80--phase0-compile-sources> ->
> 
> command: Gate target-CallbackURLKit-cabbd167fcd07023ca79fb7460ac722decb0589ae08e4a27c16de552d16baa80--phase0-compile-sources ->
> 
> node: /Users/jz/Library/Developer/Xcode/DerivedData/iShadowsocksR-acvpbhqcwpoufuaguoictgwlbiuc/Build/Intermediates.noindex/CallbackURLKit.build/Debug-iphoneos/CallbackURLKit.build/Objects-normal/arm64/CallbackURLKit_vers.o
> ```

<img width="655" alt="image" src="https://user-images.githubusercontent.com/29394995/165664745-3ca701fc-d116-4ff4-ba6d-c7c91926c819.png">
According to the prompt information to modify. "This usually can be resolved by moving the target's Headers build phase before Compile Sources."

**Comment by ssrlive** [comment]
this is the only change point for the full project. do NOT change any others. don't mind the tons of warnnings, there all can ignored.

![image](https://user-images.githubusercontent.com/30760636/166132366-e6521805-efd3-43da-b304-90cdd177049b.png)
