### ISSUE TITLE
编译成功 但是界面空白然后报 Thread 1: signal SIGABRT

### ISSUE THREAD

**Issue by azhm** [ShadowsocksR-Live/iShadowsocksR#7]
编译成功 但是界面空白 然后报  Thread 1: signal SIGABRT 
有什么地方和id关联还需要改的么
<img width="1146" alt="wx20180410-183850 2x" src="https://user-images.githubusercontent.com/12508146/38552360-7a43fb9a-3cee-11e8-9bd4-c849b34d8390.png">

**Comment by ssrlive** [comment]
以 “com.ssrlive.issr” 作為關鍵詞搜索整個工程. 改成你自己的 ID. 應該就不會報錯了. 
估計是這樣. 你不會調試程序嗎?

**Comment by azhm** [comment]
我调试了 全部都改了 也参考了谷歌上其他答案。。。还是这样报错
