### ISSUE TITLE
你好 请问有的库没有安装是怎么回事

### ISSUE THREAD

**Issue by yangdehui** [ShadowsocksR-Live/iShadowsocksR#70]
podfile Library引用的库 设置git代理后 pod install， 有的库没有安装

**Comment by ssrlive** [comment]
你在牆外的 VPS 上下載代碼吧。少很多發惱。參考這個回覆：

https://github.com/ShadowsocksR-Live/iShadowsocksR/issues/59#issuecomment-719891239

**Comment by yangdehui** [comment]
这～～ 好麻烦 我没有vps linux环境，为什么在我设了代理 pod install 引用的Library中还是有一部分开源库没有down下来，被墙了吗

**Comment by ssrlive** [comment]
對

**Comment by ccwater666** [comment]
> 这～～ 好麻烦 我没有vps linux环境，为什么在我设了代理 pod install 引用的Library中还是有一部分开源库没有down下来，被墙了吗

你设置了代理，你确定你的终端已经过代理了吗？curl https://www.google.com.hk 有数据返回吗？如果没有的话，说明你的终端是没过代理的

**Comment by yangdehui** [comment]
> 

有数据返回 看了看终端代理没问题， 老哥能否给发一份sdslydh@163.com,感谢
