### ISSUE TITLE
请问为什么没有NEIPv6Settings相关配置呢

### ISSUE THREAD

**Issue by yangdehui** [ShadowsocksR-Live/iShadowsocksR#73]

**Comment by ssrlive** [comment]
不为什么，那时还没有条件，开发者没考虑 IPv6，到现在，还是没多少使用场景。

**Comment by yangdehui** [comment]
> 不为什么，那时还没有条件，开发者没考虑 IPv6，到现在，还是没多少使用场景。

现在app内没走代理 app外走代理 请问是不是这块导致的

**Comment by yangdehui** [comment]
> 不为什么，那时还没有条件，开发者没考虑 IPv6，到现在，还是没多少使用场景。

好吧 测试 app内可以走代理， 隧道扩展不会走代理～～～
