### ISSUE TITLE
域名匹配

### ISSUE THREAD

**Issue by yangdehui** [ShadowsocksR-Live/iShadowsocksR#75]
public enum ProxyRuleType: String {
    case URLMatch = "URL-MATCH"
    case URL = "URL"
    case Domain = "DOMAIN"
    case DomainMatch = "DOMAIN-MATCH"
    case DomainSuffix = "DOMAIN-SUFFIX"
    case GeoIP = "GEOIP"
    case IPCIDR = "IP-CIDR"
}

支持Domain-Keyword吗大佬

**Comment by ssrlive** [comment]
这一块从我接手以来就没有管过，给不了你答案。
