### ISSUE TITLE
Is there any available app in AppStore?

### ISSUE THREAD

**Issue by zerodwide** [ShadowsocksR-Live/iShadowsocksR#77]
Dear @ssrlive 
I appreciate your great work. 
Is there any available app in AppStore? i have searched alot but potatso is not in app store any more
only potatso lite is available but it wont support SSRoT!
i didnot tried potatso 2, as its not free.

Android and Linux, Windows are working perfectly.
SSRoT is piece of art in whole networking history!

**Comment by ssrlive** [comment]
No mainland Chinese would dare to do this.

**Comment by zerodwide** [comment]
@ssrlive Yea it is. 
Hope for a day every person in planet be FREE!

I don't you are aware about Iran right now or not, they need to bypass restrictions.
I have been alerted that SSRoT is perfectly working in there in highest restrictions.

Do you have any suggestion on running alternatives solutions for iOS users?

Today i found OpenVPN over SS/TLS via Stunnel is good, but it also seems no client app exist on Appstore, it need to be jailbroken.

**Comment by ssrlive** [comment]
you need prepare another PC running SSRoT that listening 0.0.0.0:1080, then donwload & install [potatso lite](https://apps.apple.com/us/app/potatso-lite/id1239860606) to connect the PC. 

note: your PC and your iPhone must connect to same network.

https://github.com/ShadowsocksR-Live/shadowsocksr-native/wiki/%E5%AE%A2%E6%88%B7%E7%AB%AF%E7%94%A8%E6%B3%95#ios

![image](https://user-images.githubusercontent.com/30760636/193583484-7e57758a-f7b8-491c-9b4e-3a3827e8bef7.png)

**Comment by zerodwide** [comment]
Thanks a lot <3

**Comment by ssrlive** [comment]
Please send me you email address. I can send you something useful.
