### ISSUE TITLE
大佬，紧急求助，移植本框架到我自己App的时候，始终不能编译通过

### ISSUE THREAD

**Issue by shadow-boy** [ShadowsocksR-Live/iShadowsocksR#78]
具体路径为PacketProcessor/tun2socks-iOS/system/BAddr.h 文件报错，
附上截图部分
<img width="1043" alt="image" src="https://user-images.githubusercontent.com/15226194/195490408-af2f2bc1-4e2d-4059-87aa-7d17f9428162.png">

请问改如何处理呢、被这个问题困扰2天了

**Comment by ssrlive** [comment]
这一行明明在那里，不知道你还要啥。

https://github.com/ShadowsocksR-Live/iShadowsocksR/blob/26c92ccc4db9afce312945eb1f43cc8ceaacca98/PacketProcessor/tun2socks-iOS/system/BAddr.h#L48

**Comment by shadow-boy** [comment]
> 这一行明明在那里，不知道你还要啥。
> 
> https://github.com/ShadowsocksR-Live/iShadowsocksR/blob/26c92ccc4db9afce312945eb1f43cc8ceaacca98/PacketProcessor/tun2socks-iOS/system/BAddr.h#L48

不好意思大佬，已经build成功了，是我其他地方lib没有加上去导致的xcode在这个地方报错的，不是这个地方的问题
