### ISSUE TITLE
Build出错 - No such module 'RealmSwift'

### ISSUE THREAD

**Issue by lslzl3000** [ShadowsocksR-Live/iShadowsocksR#8]
按介绍 一步步来的，最后进xcode build时出错
我是xcode 9.3, pod 1.5.0

不知道哪里的问题，求教

**Comment by ssrlive** [comment]
全局代理。 让 pod 走代理。

**Comment by lslzl3000** [comment]
是没安装好的原因吗？应该是都完全安装了，没有出现网络问题

> Sending stats
      - Alamofire, 4.7.1
      - Appirater, 2.3.1
      - Aspects, 0.0.1
      - AsyncSwift, 2.0.4
      - Cartography, 3.0.1
      - CocoaLumberjack, 3.0.0
      - Crashlytics, 3.10.1
      - Fabric, 1.7.6
      - Helpshift, 5.6.1
      - ICDMaterialActivityIndicatorView, 0.1.3
      - ICSPullToRefresh, 0.6
      - ISO8601DateFormatter, 0.8
      - KeychainAccess, 3.1.1
      - LogglyLogger-CocoaLumberjack, 3.0.0
      - MBProgressHUD, 1.1.0
      - ObjectMapper, 3.1.0
      - PSOperations, 4.0.1
      - Realm, 2.10.2
      - RealmSwift, 2.10.2
      - Reveal-iOS-SDK, 1.6.2
      - SwiftColor, 0.6.0
 Pod installation complete! There are 21 dependencies from the Podfile and 22 total pods installed.

**Comment by ssrlive** [comment]
估計你近視眼 `Potatso.xcworkspace`!!!

**Comment by lslzl3000** [comment]
🙃 哈哈 好吧 我错了~~ 不太熟悉xcode
