### ISSUE TITLE
踩坑：关于国内访问不走代理的办法

### ISSUE THREAD

**Issue by BJGX** [ShadowsocksR-Live/iShadowsocksR#82]
加入一个白名单whiteList， 把需要忽略的网站加入进去
然后修改rfc2553_connect_to 这个函数里面有个判断是否代理ROUTE_PROXY ，ROUTE_DIRECT 如果是国内的网站就判断走ROUTE_DIRECT， 否则就是ROUTE_PROXY

**Comment by ssrlive** [comment]
Potatso 古老的代碼，我已經沒有動力去看了。一定要死磕的話，你自求多福吧。
