### ISSUE TITLE
Undefined symbol: _OBJC_CLASS_$_DDASLLogger

### ISSUE THREAD

**Issue by 66pig** [ShadowsocksR-Live/iShadowsocksR#85]
编译的时候报错：
Undefined symbol: _OBJC_CLASS_$_DDASLLogger
Undefined symbol: _OBJC_CLASS_$_DDLog

<img width="389" alt="debug" src="https://user-images.githubusercontent.com/27850670/227757057-d4438def-f5e1-42cc-994b-cd8df319f5ab.png">

**Comment by ssrlive** [comment]
清理 构建 文件夹 后, 如何? `Clean Build Folder...`

我这里 Xcode 14.3 没问题.
