### ISSUE TITLE
Snapchat 无法使用

### ISSUE THREAD

**Issue by aishuidedabai** [ShadowsocksR-Live/iShadowsocksR#9]
global-mode 为1 的情况下无法发送消息（其实软件本身发送消息是不需要翻墙的），global-mode为0即可。问题应该出在TCP

**Comment by ssrlive** [comment]
你自行集成的 ssrNative 有解決嗎? 有的話分享出來?

**Comment by aishuidedabai** [comment]
怎么发给你，另外cdef没法用，为啥，为什么服务器说tcp header错误

**Comment by ssrlive** [comment]
提交pr 。 cdef 是啥不知道。

**Comment by aishuidedabai** [comment]
auth_chain_*

**Comment by ssrlive** [comment]
你得首先安装 ssrr 团队维护的服务器，才能使用 cdef 系列协议。
ssrr python 版的 某个分支。

**Comment by aishuidedabai** [comment]
哦哦，是服务器安装的问题，并非是代码的问题

**Comment by ssrlive** [comment]
你如果有爱心，可以把 ssrr 的python代码合并过来。

**Comment by pang-w** [comment]
@aishuidedabai  请问您是如何解决这个问题的呢？

@ssrlive 你好，貌似现在的版本并没有解决这个问题。
