### ISSUE TITLE
auth_aes128_md5协议无法打开网页

### ISSUE THREAD

**Issue by yshhFukui** [ShadowsocksR-Live/iShadowsocksR#92]
大佬，真机调试 加密方式选chacha20 协议选auth_aes128_md5 混淆选tls1.2_ticket_auth 不能能正常打开网页。尝试auth_chain_a，没问题，可以打开网页，求助！！

**Comment by ssrlive** [comment]
如果你的服務端不是 ssr-native 或者 overtls ， 這些奇奇怪怪的問題我無法保證可以解開。目前 C 語言寫成的 ssr-native 已經處於最低維護階段了。建議你安裝 overtls 服務端，再 用你的手機連上測試。
