### ISSUE TITLE
iOS的ACL分流被阉割掉了吗

### ISSUE THREAD

**Issue by yangdehui** [ShadowsocksR-Live/iShadowsocksR#93]
https://github.com/ShadowsocksR-Live/ssrDroid

**Comment by yangdehui** [comment]
https://github.com/ShadowsocksR-Live/ssrDroid
我看安卓版本是支持ACL分流的

**Comment by ssrlive** [comment]
閹割了。

**Comment by yangdehui** [comment]
> 閹割了。
那大佬我想从现在iOS版本基础上添加ACL分流，需要用到哪块相关库呢，麻烦指导下

**Comment by ssrlive** [comment]
刪掉裏面的 privoxy 模塊，用這個 https://github.com/ssrlive/socks-hub 代替，並且自己加上分流的功能。

**Comment by ssrlive** [comment]
比較有挑戰性，好好玩。

**Comment by yangdehui** [comment]
> 閹割了。



> 刪掉裏面的 privoxy 模塊，用這個 https://github.com/ssrlive/socks-hub 代替，並且自己加上分流的功能。

非常感谢，我研究研究

**Comment by yangdehui** [comment]
> 刪掉裏面的 privoxy 模塊，用這個 https://github.com/ssrlive/socks-hub 代替，並且自己加上分流的功能。

大佬，没找到你说的privoxy模块，能给个索引不

**Comment by yangdehui** [comment]
> > 刪掉裏面的 privoxy 模塊，用這個 https://github.com/ssrlive/socks-hub 代替，並且自己加上分流的功能。
> 
> 大佬，没找到你说的privoxy模块，能给个索引不

找到了，能用项目里的Rule规则做分流吗emmm ，感觉达不到分流的效果
