### ISSUE TITLE
How can i support v2Ray in this current project ?

### ISSUE THREAD

**Issue by AnitaGVMTechnologies** [ShadowsocksR-Live/iShadowsocksR#94]
Hi there
I am able to sucessfully integrate the project and able to run but i need v2Ray support in this application

How can i add v2ray support please guide me !!

#helpwanted

**Comment by ssrlive** [comment]
replace ssr-client core with v2ray core, since they are all standard socks5 server.

**Comment by AnitaGVMTechnologies** [comment]
<img width="744" alt="Screenshot 2024-02-09 at 5 06 27 PM" src="https://github.com/ShadowsocksR-Live/iShadowsocksR/assets/133353238/05151d41-24ec-4747-b2ae-e2422e1e044d">

You are talking about this ?

**Comment by AnitaGVMTechnologies** [comment]
Or could you please guide me by providing right v2ray core zip and provide steps like how i can replace and where and what exactly i need to do as i am new into that

**Comment by ssrlive** [comment]
This is the entry of SSR or OverTLS client.

https://github.com/ShadowsocksR-Live/iShadowsocksR/blob/6a78b510a2bd03c17ca342d31da0c18f332977d6/PacketTunnel/ProxyManager.m#L133-L167

look it yourself. I have no time to teach you.
