### ISSUE TITLE
(NSError?) _lastDisconnectError = domain: "NEVPNConnectionErrorDomainPlugin" - code: 6 

### ISSUE THREAD

**Issue by AnitaGVMTechnologies** [ShadowsocksR-Live/iShadowsocksR#95]
I am successfully able to compile and run the project 
I am also successfully added the Proxy VPN but when i click on connect button neither it connect nore it specifically gave any such error 

I found the above error while debug 

Can you help me when such error occurs ?

@ssrlive I need your help here

**Comment by ssrlive** [comment]
This app must run in a real iPhone and you must ba a apple developer of $99 per year.

**Comment by AnitaGVMTechnologies** [comment]
I am running in real iphone only and i have membership account in apple too

I have replace all my certificates , profile and bundle identifier in app and able to run into my device but as i mentioned i am not able to connect where on live app i can able to connect , so i need help here
