### ISSUE TITLE
大佬好，相同配置在 macbook 连接正常，但 iOS loading 无法连接，请问是什么原因引起的？

### ISSUE THREAD

**Issue by zhouxhu** [ShadowsocksR-Live/iShadowsocksR#98]
Xcode 版本：15.3
iOS 版本：17.3
对比参数，都是相同的，本地参数写死，iOS 也是一直 loading。

<img width="1129" alt="image" src="https://github.com/ShadowsocksR-Live/iShadowsocksR/assets/9824674/2fa29fb3-7109-43e8-bced-039d332656f0">

<img width="599" alt="image" src="https://github.com/ShadowsocksR-Live/iShadowsocksR/assets/9824674/601705cf-82b3-48f7-82de-b451b156b547">

**Comment by ssrlive** [comment]
估计你的设置有问题：

![image](https://github.com/ShadowsocksR-Live/iShadowsocksR/assets/30760636/9e56e6fb-af16-4468-baac-9c9680fed729)

**Comment by ssrlive** [comment]
这就是当前的代码版本，在我手机上很正常。

![image](https://github.com/ShadowsocksR-Live/iShadowsocksR/assets/30760636/6cccca93-3eba-4a39-a3ab-19e9249847d2)

**Comment by ssrlive** [comment]
tunnel_path 字段不要有奇怪的东西，字母数字就可以了。

**Comment by zhouxhu** [comment]
请问，在 iOS 中client_settings 中 listen_port、client_id ，这些字段不用配置么？

**Comment by ssrlive** [comment]
listen_port 会被改成 0 的，这样就会监听在随机的一个有效端口上。 client_id 是为将来的机场准备的，目前没使用。

**Comment by ssrlive** [comment]
shadowsocks_handler 回调函数就是接收 具体端口用的，如果回调返回后，后续的动作才可以展开。
